### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'testing/data/exp_abinitio_volumes/10345_neural_volume/drgn_result/config.pkl'

### ISSUE THREAD

**Issue by riku359** [Cellverse/CryoGEM#2]
I ran this
`cryogem gen_data --mode hetero --device cuda:0 --drgn_epoch 49 \
--drgn_dir testing/data/exp_abinitio_volumes/10345_neural_volume/drgn_result \
--save_dir save_images/gen_data/Integrin\(10345\)/training_dataset/ \
--n_micrographs 100 --particle_size 100 --mask_threshold 0.7 \
--symmetry C1 --micrograph_size 1024 --particles_mu 42.41 --particles_sigma 17.45 --particle_collapse_ratio 0.40`

But I faced following error.
`FileNotFoundError: [Errno 2] No such file or directory: 'testing/data/exp_abinitio_volumes/10345_neural_volume/drgn_result/config.pkl'`

I would appreciate it if you could tell me the solution.

**Comment by Jiakai-Zhang** [comment]
Thanks for pointing this out! It seems like we've missed to upload one config file located in `testing/data/exp_abinitio_volumes/10345_neural_volume/drgn_result/config.yaml`.

Could you please try to create this file and copy & paste the following content, and run your command again? On my side, I can your command to generate data successfully. 
```
cmd:
- /home/vrlab/.conda/envs/genem/bin/cryodrgn
- train_vae
- ../GenEM/testing/data/Integrin(10345)/particles.100.mrc
- --poses
- ../GenEM/testing/data/Integrin(10345)/poses.pkl
- --ctf
- ../GenEM/testing/data/Integrin(10345)/ctfs.pkl
- --zdim
- '8'
- -n
- '50'
- --enc-dim
- '1024'
- --enc-layers
- '3'
- --dec-dim
- '1024'
- --dec-layers
- '3'
- -b
- '32'
- --no-amp
- -o
- ./10345_neural_volume/drgn_result
dataset_args:
  ctf: /media/vrlab/My Passport/GenEM/testing/data/Integrin(10345)/ctfs.pkl
  datadir: null
  do_pose_sgd: false
  ind: null
  invert_data: true
  keepreal: false
  norm:
  - 0.0
  - 27.351064682006836
  particles: /media/vrlab/My Passport/GenEM/testing/data/Integrin(10345)/particles.100.mrc
  poses: /media/vrlab/My Passport/GenEM/testing/data/Integrin(10345)/poses.pkl
  window: true
  window_r: 0.85
lattice_args:
  D: 101
  extent: 0.5
  ignore_DC: true
model_args:
  activation: relu
  domain: fourier
  enc_mask: 50
  encode_mode: resid
  feat_sigma: 0.5
  pdim: 1024
  pe_dim: null
  pe_type: gaussian
  players: 3
  qdim: 1024
  qlayers: 3
  zdim: 8
seed: 31102
time: 2024-03-17 19:39:08.217856
version: 2.3.0
```
